inlet_gas:
  T_in: 900.0         # K
  P_in: 105000.0      # Pa
  m_dot: 5.0          # kg/s
  composition:        # mole fractions
    CO2: 0.09
    H2O: 0.18
    O2: 0.03
    N2: 0.70

drums:
  - id: "drum1"
    pressure: 1500000.0          # Pa
    level: 0.8                   # m liquid height
    geometry:
      diameter: 1.5              # m
      length: 6.0                # m
      nozzle_data:
        steam_outlet:
          Dn: 0.2                # m
        water_inlet:
          Dn: 0.15               # m
    initial_water_inventory: 1.0  # m^3

stages:
  - type: tube_bank
    flow: co_current
    geometry:
      L: 6.0            # m
      Di: 0.038         # m
      Do: 0.045         # m
      Ntubes: 220
      pitch: 0.065      # m
      arrangement: triangular
      roughness: 1.0e-5 # m
      thickness: 0.0035 # m (wall)
      frontal_width: 1.6 # m
      frontal_height: 1.2
    correlations:
      h_gas: gnielinski
      epsilon_gas: leckner
      h_water_boiling: chen
      friction: colebrook_white
    losses:
      - element: inlet_header
        K: 0.5
      - element: outlet_header
        K: 1.0
    fouling:
      R_fg: 2.0e-4      # m^2·K/W gas-side
      R_fw: 1.0e-4      # m^2·K/W water-side
    discretization:
      N_cells: 60

  - type: reversal_chamber
    flow: co_current
    geometry:
      L_eq: 2.0         # m equivalent
      Dh: 1.0           # m hydraulic diameter
      area_flow: 1.2         # m^2
      area_ht: 1.2        # m^2
    correlations:
      h_gas: churchill_bernstein
      epsilon_gas: smith
      h_water_boiling: thom
      friction: churchill
    losses:
      - element: 180deg_bend
        K: 1.6
      - element: expansion
        K: 0.3
    fouling:
      R_fg: 1.5e-4
      R_fw: 1.0e-4
    discretization:
      N_cells: 10

  - type: single_tube
    flow: co_current
    geometry:
      L: 5.0            # m
      Di: 0.032         # m
      Do: 0.038         # m
      roughness: 1.0e-5 # m
      thickness: 0.003  # m
      R_fg: 1.0e-4
      R_fw: 1.0e-4
    correlations:
      h_gas: dittus_boelter
      epsilon_gas: wsggm_simple
      h_water_boiling: gungor_winterton
      friction: haaland
    losses:
      - element: entrance
        K: 0.5
      - element: exit
        K: 1.0
    fouling:
      R_fg: 1.0e-4
      R_fw: 1.0e-4
    discretization:
      N_cells: 50
