[gas_side]
mass_flow_rate = "9.427"
inlet_temperature = "2176.59"
inlet_pressure = "115000"

[gas_side.composition]
CO2 = "0.089497"
H2O = "0.170469"
N2 = "0.713727"
O2 = "0.017384"
Ar = "0.008489"
SO2 = "0.00435"

[gas_side.spectroscopic_data]
CO2 = "0.05"
H2O = "0.5"
N2 = "0.000001"
O2 = "0.001"
Ar = "0.0"
SO2 = "0.3"

[water_side]
mass_flow_rate = "3.333"         # [kg/s]
inlet_temperature = "378.15"       # [K]
outlet_temperature = "443.15"      # [K]
pressure = "1000000"             # [Pa]
mu_exp = "1"
C_sf = "1"
n = "1"

[water_side.composition]   # leave empty for pure water
# NaCl = ""
# CaCO3 = ""
# SiO2 = ""

[environment]
ambient_temperature = "298.15"             # [K]
radiative_temperature = "298.15"           # Trad,∞ [K]
external_emissivity = "0.85"            # [-]
external_h = "8"                        # [W/(m^2·K)]
radiation_view_factor_external = "1.0"  # [-]

# ---------- STAGES ----------

[stages.drum.geometry]
inner_diameter = "3.150"
inner_length = "5.620"
[stages.drum.geometry.wall.properties]
thickness = "0.010"
conductivity = "45"

[stages.drum.surfaces.inner]
roughness = "0.00002"         # [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.drum.surfaces.outer]
roughness = "0.00002"         # [m]
emissivity = "0.85"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass1.geometry]
inner_diameter = "1.4"
inner_length = "5.276"
number_of_tubes = "1"
layout = "triangular"
pitch = "0.029"
[stages.pass1.geometry.wall.properties]
thickness = "0.0029"
conductivity = "16"

[stages.pass1.surfaces.inner]
roughness = "0.000015"        # tube ID roughness [m]
emissivity = "0.30"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass1.surfaces.outer]
roughness = "0.000015"        # tube OD roughness [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.reversal1.geometry]
inner_diameter = "0.80"       # [m]
inner_length = "1.0"          # [m]
[stages.reversal1.geometry.wall.properties]
thickness = "0.012"           # [m]
conductivity = "45"           # [W/(m·K)]

[stages.reversal1.nozzles.inlet]
diameter = "0.40"             # [m]
length = "0.50"               # [m]

[stages.reversal1.nozzles.outlet]
diameter = "0.40"             # [m]
length = "0.50"               # [m]

[stages.reversal1.surfaces.inner]
roughness = "0.00002"         # [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.reversal1.surfaces.outer]
roughness = "0.00002"         # [m]
emissivity = "0.85"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass2.geometry]
inner_diameter = "0.076"
inner_length = "4.975"
number_of_tubes = "118"
layout = "triangular"
pitch = "0.029"
[stages.pass2.geometry.wall.properties]
thickness = "0.0029"
conductivity = "16"

[stages.pass2.surfaces.inner]
roughness = "0.000015"        # [m]
emissivity = "0.30"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass2.surfaces.outer]
roughness = "0.000015"        # [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.reversal2.geometry]
inner_diameter = "0.80"       # [m]
inner_length = "1.0"          # [m]
[stages.reversal2.geometry.wall.properties]
thickness = "0.012"           # [m]
conductivity = "45"           # [W/(m·K)]

[stages.reversal2.nozzles.inlet]
diameter = "0.40"             # [m]
length = "0.50"               # [m]

[stages.reversal2.nozzles.outlet]
diameter = "0.40"             # [m]
length = "0.50"               # [m]

[stages.reversal2.surfaces.inner]
roughness = "0.00002"         # [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.reversal2.surfaces.outer]
roughness = "0.00002"         # [m]
emissivity = "0.85"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass3.geometry]
inner_diameter = "0.076"
inner_length = "5.620"
number_of_tubes = "100"
layout = "triangular"
pitch = "0.029"
[stages.pass3.geometry.wall.properties]
thickness = "0.0029"
conductivity = "16"

[stages.pass3.surfaces.inner]
roughness = "0.000015"        # [m]
emissivity = "0.30"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]

[stages.pass3.surfaces.outer]
roughness = "0.000015"        # [m]
emissivity = "0.80"           # [-]
fouling_thickness = "0.0001"  # [m]
fouling_conductivity = "0.20" # [W/(m·K)]
