[gas_side]
mass_flow_rate = "kg/s"
inlet_temperature = "K"
inlet_pressure = "Pa"

[gas_side.composition]          # mole fractions
CO2 = "1"
H2O = "1"
N2  = "1"
O2  = "1"
CO  = "1"
H2  = "1"
CH4 = "1"
Ar  = "1"

[water_side]
mass_flow_rate = "kg/s"
inlet_temperature = "K"
outlet_temperature = "K"
pressure = "Pa"
superheat = "1"
mu_exp = "1"
C_sf = "1"
n = "1"

[water_side.composition]
NaCl = "1"
CaCO3 = "1"
SiO2 = "1"

[environment]
ambient_temperature = "K"
radiative_temperature = "K"
external_emissivity = "1"
external_h = "W/(m**2*K)"
radiation_view_factor_external = "1"

[stages.drum.geometry]
inner_diameter = "m"
inner_length = "m"
[stages.drum.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.drum.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.drum.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass1.geometry]
inner_diameter = "m"
inner_length = "m"
number_of_tubes = "1"
layout = "category"
pitch = "m"
[stages.pass1.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.pass1.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass1.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.reversal1.geometry]
inner_diameter = "m"
inner_length = "m"
[stages.reversal1.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.reversal1.nozzles.inlet]
diameter = "m"
length = "m"

[stages.reversal1.nozzles.outlet]
diameter = "m"
length = "m"

[stages.reversal1.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.reversal1.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass2.geometry]
inner_diameter = "m"
inner_length = "m"
number_of_tubes = "1"
layout = "category"
pitch = "m"
[stages.pass2.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.pass2.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass2.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.reversal2.geometry]
inner_diameter = "m"
inner_length = "m"
[stages.reversal2.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.reversal2.nozzles.inlet]
diameter = "m"
length = "m"

[stages.reversal2.nozzles.outlet]
diameter = "m"
length = "m"

[stages.reversal2.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.reversal2.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass3.geometry]
inner_diameter = "m"
inner_length = "m"
number_of_tubes = "1"
layout = "category"
pitch = "m"
[stages.pass3.geometry.wall.properties]
thickness = "m"
conductivity = "W/(m*K)"

[stages.pass3.surfaces.inner]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"

[stages.pass3.surfaces.outer]
roughness = "m"
emissivity = "1"
fouling_thickness = "m"
fouling_conductivity = "W/(m*K)"
